name: Pre-Released

on:
  release:
    types: [prereleased]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - name: Info
        run: |
          echo Runing pre-release

      - uses: actions/checkout@v3

      - name: Cached Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            nodeModules-

      - name: Install Deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      # - name: Set Version
      #   run: npm --prefix ./aws-cdk version ${{ github.ref_name }}

      - name: Build Plugin
        run: npx nx run aws-cdk:build --outputPath ./build/aws-cdk

      - name: Publish Plugin
        run: npx nx run aws-cdk:publish  --ver=${{ github.ref_name }} --tag=beta
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
