name: Released

on:
  release:
    types: [released]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - name: Info
        run: |
          echo Runing release

      - uses: actions/checkout@v3

      - name: Cached Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}
          restore-keys: |
            nodeModules-

      - name: Install Deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Set Version
        run: npm --prefix ./packages/${{github.event.release.name}} version ${{ github.ref_name }}

      - name: Build Plugin
        run: npx nx run ${{github.event.release.name}}:build --outputPath ./build/${{github.event.release.name}}

      - name: Npm Auth
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@aws-nx'

      - name: Publish Plugin
        run: npx nx run ${{ github.event.release.name }}:publish  --ver=${{ github.ref_name }} --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
